-- Create replication user for Debezium
CREATE USER ${POSTGRES_REPLICATION_USER} WITH REPLICATION ENCRYPTED PASSWORD '${POSTGRES_REPLICATION_PASSWORD}';
GRANT CONNECT ON DATABASE healthcare TO ${POSTGRES_REPLICATION_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_REPLICATION_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_REPLICATION_USER};
CREATE PUBLICATION dbz_publication FOR ALL TABLES;
